// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Measurement;
@class MeasurementBuilder;



@interface MeasurementRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Measurement_image @"image"
#define Measurement_side_a @"sideA"
#define Measurement_side_b @"sideB"
@interface Measurement : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSideA_:1;
  BOOL hasSideB_:1;
  BOOL hasImage_:1;
  BOOL sideA_:1;
  BOOL sideB_:1;
  NSData* image;
}
- (BOOL) hasImage;
- (BOOL) hasSideA;
- (BOOL) hasSideB;
@property (readonly, strong) NSData* image;
- (BOOL) sideA;
- (BOOL) sideB;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MeasurementBuilder*) builder;
+ (MeasurementBuilder*) builder;
+ (MeasurementBuilder*) builderWithPrototype:(Measurement*) prototype;
- (MeasurementBuilder*) toBuilder;

+ (Measurement*) parseFromData:(NSData*) data;
+ (Measurement*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Measurement*) parseFromInputStream:(NSInputStream*) input;
+ (Measurement*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Measurement*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Measurement*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MeasurementBuilder : PBGeneratedMessageBuilder {
@private
  Measurement* resultMeasurement;
}

- (Measurement*) defaultInstance;

- (MeasurementBuilder*) clear;
- (MeasurementBuilder*) clone;

- (Measurement*) build;
- (Measurement*) buildPartial;

- (MeasurementBuilder*) mergeFrom:(Measurement*) other;
- (MeasurementBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MeasurementBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasImage;
- (NSData*) image;
- (MeasurementBuilder*) setImage:(NSData*) value;
- (MeasurementBuilder*) clearImage;

- (BOOL) hasSideA;
- (BOOL) sideA;
- (MeasurementBuilder*) setSideA:(BOOL) value;
- (MeasurementBuilder*) clearSideA;

- (BOOL) hasSideB;
- (BOOL) sideB;
- (MeasurementBuilder*) setSideB:(BOOL) value;
- (MeasurementBuilder*) clearSideB;
@end


// @@protoc_insertion_point(global_scope)
