platform :ios, '8.0'
inhibit_all_warnings!
xcodeproj 'AbelReactivePlayground'

target :AbelReactivePlayground do

    pod 'ReactiveCocoa', '~> 2.3.1'

end

post_install do |installer|
installer.project.targets.each do |target|
puts "#{target.name}"
end
end
